# Generated by Django 3.2.2 on 2022-01-25 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('phone_no', models.CharField(blank=True, max_length=10)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('aadhar', models.CharField(blank=True, max_length=12)),
                ('site_name', models.CharField(blank=True, max_length=200)),
                ('area', models.IntegerField(blank=True)),
                ('status', models.CharField(blank=True, choices=[('rejected', 'Rejected'), ('pending', 'pending'), ('accepted', 'accepted')], default='pending', max_length=10)),
                ('payment_status', models.BooleanField(blank=True, default=False)),
                ('form', models.FileField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firenoc_app.application')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
