# Generated by Django 3.2.2 on 2022-01-25 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firenoc_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='area',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
