# Generated by Django 3.2.2 on 2022-01-25 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firenoc_app', '0003_alter_application_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='aadhar',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_no',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firenoc_app.application'),
        ),
    ]
