# Generated by Django 3.2.2 on 2022-01-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firenoc_app', '0004_auto_20220125_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='application',
        ),
        migrations.AddField(
            model_name='customuser',
            name='application',
            field=models.ManyToManyField(null=True, to='firenoc_app.Application'),
        ),
    ]
